<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Zapnout';
$labels['twofactor_gauthenticator'] = 'Dvoufázové ověření';
$labels['code'] = 'Google Authenticator kód';

$labels['two_step_verification_form'] = 'Kód dvoufázového ověření:';

$labels['secret'] = 'Tajný klíč';
$labels['qr_code'] = 'QR kód';
$labels['msg_infor'] = 'Zobrazený QR kód, obsahující nastavení pro dvoufázové ověření, můžete použít v TOTP kompatibilní aplikaci jako je <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>.';

$labels['show_secret'] = 'Zobrazit tajný klíč';
$labels['hide_secret'] = 'Skrýt tajný klíč';
$labels['create_secret'] = 'Vytvořit tajný klíč';

$labels['new_secret'] = 'Vygenerovat nový tajný klíč';

$labels['show_qr_code'] = 'Zobrazit QR kód';
$labels['hide_qr_code'] = 'Skrýt QR kód';

$labels['recovery_codes'] = 'Kódy pro obnovení';
$labels['show_recovery_codes'] = 'Zobrazit kódy pro obnovení';
$labels['hide_recovery_codes'] = 'Skrýt kódy pro obnovení';

$labels['setup_all_fields'] = 'Vyplňte všechna pole (a ujistěte se, že jste klikli na tlačítko Uložit)';

$labels['enrollment_dialog_title'] = 'Registrace dvoufázového ověření';
$labels['enrollment_dialog_msg'] = '<strong>Kódy dvoufázového ověření</strong> jsou vyžadovány pro vyšší zabezpečení. Prosím, nastavte je nyní.';

$labels['check_code'] = 'Zkontrolovat kód';
$labels['code_ok'] = 'Správný kód';
$labels['code_ko'] = 'Špatný kód';

$labels['dont_ask_me_days'] = 'Neptat se na tomto stroji znovu na kódy následujích {DAYS} dnů';

$labels['check_code_to_activate'] = 'Pro uložení, naskenujte QR kód a vložte následně vygenerovaný dvoufázový kód níže.';

$labels['test_passcode'] = 'Zde můžete otestovat vygenerovaný ověřovací kód';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Nastavení dvoufázového ověření bylo úspěšně uloženo.';

