<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activate';
$labels['twofactor_gauthenticator'] = 'Two-Factor Authentication (2FA)';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = 'Two-Factor Authentication (2FA):';

$labels['secret'] = 'Secret key';
$labels['qr_code'] = 'QR Code';
$labels['msg_infor'] = 'You can scan this QR code containing the Two-Factor Authentication (2FA) settings using a TOTP compatible app such as Google Authenticator <a href="https://apps.apple.com/us/app/google-authenticator/id388497605" target="_blank">
App Store</a> or <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US" target="_blank">
Google Play</a>';

$labels['show_secret'] = 'Show secret key';
$labels['hide_secret'] = 'Hide secret key ';
$labels['create_secret'] = 'Create secret key';

$labels['new_secret'] = 'Generate New Secret key';

$labels['show_qr_code'] = 'Show QR Code';
$labels['hide_qr_code'] = 'Hide QR Code';

$labels['recovery_codes'] = 'Recovery codes';
$labels['remaining_recovery_codes'] = 'Remaining recovery codes';
$labels['show_recovery_codes'] = 'Show recovery codes';
$labels['hide_recovery_codes'] = 'Hide recovery codes';
$labels['new_recovery_codes'] = 'Generate New recovery codes';

$labels['setup_all_fields'] = 'Fill all fields (make sure you click save to store your settings)';

$labels['enrollment_dialog_title'] = '2-Factor authentication enrollment';
$labels['enrollment_dialog_msg'] = '<strong>Two-Factor Authentication (2FA) codes</strong> are required for increased security, please configure them now.';

$labels['check_code'] = 'Check code';
$labels['code_ok'] = 'Code OK';
$labels['code_ko'] = 'Incorrect code';

$labels['dont_ask_me_days'] = 'Don&#39;t ask me codes again on this computer for {DAYS} days';

$labels['check_code_to_activate'] = 'To save, please scan the QR Code and enter the current 2-Factor code below.';

$labels['test_passcode'] = 'Test the generated Passcode here';

$labels['proceed'] = 'Proceed';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = '2-Factor authentication settings saved successfully.';

