<?php

$labels = array();
$labels['activate'] = 'Kích hoạt';
$labels['twofactor_gauthenticator'] = 'Xác thực (2FA)';
$labels['code'] = 'Mã Google Authenticator';

$labels['two_step_verification_form'] = 'Mã xác thực (2FA):';

$labels['secret'] = 'Mã bí mật';
$labels['qr_code'] = 'Mã QR';
$labels['msg_infor'] = 'Bạn có thể quét mã QR này chứa các cài đặt xác thực 2 yếu tố bằng một ứng dụng TOTP tương thích như <strong>Google Authenticator</strong> trên <a href="https://apps.apple.com/us/app/google-authenticator/id388497605" target="_blank">
App Store</a> hoặc <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US" target="_blank">
Google Play</a>';

$labels['show_secret'] = 'Hiển thị khóa bí mật';
$labels['hide_secret'] = 'Ẩn khóa bí mật';
$labels['create_secret'] = 'Tạo khóa bí mật';

$labels['new_secret'] = 'Tạo khóa bí mật mới';

$labels['show_qr_code'] = 'Hiển thị mã QR';
$labels['hide_qr_code'] = 'Ẩn mã QR';

$labels['recovery_codes'] = 'Mã khôi phục';
$labels['remaining_recovery_codes'] = 'Số lần nhập mã khôi phục còn lại';
$labels['show_recovery_codes'] = 'Hiển thị mã khôi phục';
$labels['hide_recovery_codes'] = 'Ẩn mã khôi phục';
$labels['new_recovery_codes'] = 'Tạo mã khôi phục mới';

$labels['setup_all_fields'] = 'Điền tất cả các trường (hãy chắc chắn bạn đã nhấn lưu để lưu cài đặt của bạn)';

$labels['enrollment_dialog_title'] = 'Đăng ký xác thực 2 yếu tố';
$labels['enrollment_dialog_msg'] = '<strong>Các mã xác thực 2 yếu tố</strong> được yêu cầu để tăng cường bảo mật, vui lòng cấu hình ngay bây giờ.';

$labels['check_code'] = 'Kiểm tra mã';
$labels['code_ok'] = 'Mã hợp lệ';
$labels['code_ko'] = 'Mã không hợp lệ';

$labels['dont_ask_me_days'] = 'Không hỏi mã lại trên máy tính này trong {DAYS} ngày';

$labels['check_code_to_activate'] = 'Để lưu, vui lòng quét mã QR và nhập mã xác thực 2 yếu tố vào bên dưới.';

$labels['test_passcode'] = 'Kiểm tra mã được tạo ở đây';

$labels['proceed'] = 'Tiếp tục';

$messages = array();
$messages['successfully_saved'] = 'Cài đặt xác thực 2 yếu tố đã được lưu thành công.';


